version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: 123
      POSTGRES_DB: slack
  web:
    image: slack-clone-server
    ports:
      - '3000:8081'
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet:
